server:
	http_listen_port: 9080
	grpc_listen_port: 0

positions:
	filename: /tmp/positions.yaml

clients:
	- url: http://13.125.29.61:3100/loki/api/v1/push

scrape_configs:
	- job_name: spring-boot-logs
	  docker_sd_configs:
		- host: unix:///var/run/docksr/sock
		  refresh_interval: 5s
	  relabel_configs:
		- source_labels: ['__meta_docker_container_name']
		  regex: '/(my-spring-app)' # MySpringApp을 컨테이너 이름으로 변경
		  action: keep
